name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
  
  shellcheck:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: shellcheck install-guard.sh

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  aws-guard-rules-registry-ubuntu-integration-tests:
    name: Integration tests against aws-guard-rules-registry on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: cloudformation-guard
      - name: Build
        run: |
          cd cloudformation-guard
          cargo build --release
      - uses: actions/checkout@v3
        with:
          name: aws-cloudformation/aws-guard-rules-registry
          ref: refs/tags/1.0.2
          path: aws-guard-rules-registry
      - name: First integration test
        run: |
          cloudformation-guard/target/release/cfn-guard test -d aws-guard-rules-registry/rules
          STATUS_CODE=$?
          if [ $STATUS_CODE -ne 0 ]; then
              echo "The aws-guard-rules-registry integration tests with Ubuntu have failed."
              exit 1
          else
              echo "The aws-guard-rules-registry integration tests with Ubuntu have passed."
          fi