name: Rust

on:
  push:
    branches: [ 2.x.x ]
  pull_request:
    branches: [ 2.x.x ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build all crates & run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build all crates
      run: cargo build --release --verbose
    - name: Run unit tests
      run: cargo test --verbose
  
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: shellcheck install-guard.sh

  formatting:
    name: Formatting check (cargo fmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

          
          
