name: Rust

on:
  push:
    branches: [ rules-registry-integration-tests  ]
  pull_request:
    branches: [ rules-registry-integration-tests  ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build all crates & run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build all crates
      run: cargo build --release --verbose
    - name: Run unit tests
      run: cargo test --verbose
  
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck
      run: shellcheck install-guard.sh

  formatting:
    name: Formatting check (cargo fmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  aws-guard-rules-registry-ubuntu-integration-tests:
    name: Integration tests against aws-guard-rules-registry on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout cfn-guard
        with:
          path: cloudformation-guard
      - name: Build binary
        run: |
          cd cloudformation-guard/guard/
          cargo build --release
      - uses: actions/checkout@v3
        name: Checkout aws-guard-rules-registry
        with:
          repository: aws-cloudformation/aws-guard-rules-registry
          path: aws-guard-rules-registry
          ref: main
      - name: Run integration tests using test command
        continue-on-error: true
        run: |
          cloudformation-guard/target/release/cfn-guard test -d aws-guard-rules-registry/rules
          STATUS_CODE=$?
          if [ $STATUS_CODE -ne 0 ]; then
              echo "The aws-guard-rules-registry integration tests for test command with Ubuntu have failed."
              exit 1
          else
              echo "The aws-guard-rules-registry integration tests for test command with Ubuntu have passed."
          fi
      - name: Run integration tests using parse-tree command
        continue-on-error: true
        run: |
          cd aws-guard-rules-registry/rules
          
          FAILED_RULES=()
          rules=( $(find . -type f -name "*.guard") )
          
          for rule in "${rules[@]}"
          do
              ../../cloudformation-guard/target/release/cfn-guard parse-tree \
                  --rules $rule
              
              STATUS_CODE=$?
              if [ $STATUS_CODE -ne 0 ]; then
                  FAILED_RULES+=("$rule")
              fi
          done
          
          FAILED_RULE_COUNT=${#FAILED_RULES[@]}
          
          if [ $FAILED_RULE_COUNT -gt 0 ]; then
              echo "The following $FAILED_RULE_COUNT rule(s) from aws-guard-rules-registry have failed the parse-tree 
              integration tests on Ubuntu with a non-zero error code:"
              for failed_rule in "${FAILED_RULES[@]}"
              do
                  echo $failed_rule
              done
              exit 1
          else
              echo "All the rules from aws-guard-rules-registry have succeeded the parse-tree integration tests 
              on Ubuntu."
          fi